# Test against the latest version of this Node.js version
image: Visual Studio 2019
environment:
  CFX_LITE_NODE_ENV: debug
  matrix:
    - node_version: "16"
# branches:
#   only:
#     - master
#     - '/v[0-9]+(\.[0-9]+)*/'
install:
  - ps: "Install-Product node $env:node_version"
  - yarn install --frozen-lockfile
build_script:
  - node test.js
test_script:
  - ls ~/.conflux-bin/conflux/run
cache:
  - node_modules
  - "%LOCALAPPDATA%/Yarn"
